### ISSUE TITLE
Cozmo SDK Installation Guide update

### ISSUE THREAD

**Issue by mattzjack** [anki/cozmo-python-sdk#100]
On the [page](http://cozmosdk.anki.com/docs/adb.html#macos-installation) for android debug bridge, step one says
`brew install android-platform-tools`
Apparently, brew has migrated it to cask, so this should probably be updated to something like
`brew tap caskroom/cask`
`brew cask install android-sdk`
`brew cask install android-platform-tools`
([src](https://github.com/Homebrew/homebrew-core/issues/11656))

**Comment by MarkWesleyAtAnki** [comment]
Thanks - we've modified the install instructions to include "brew tap caskroom/cask" so that it works with the latest brew changes.
