### ISSUE TITLE
update-alternatives error on Ubuntu 14.04

### ISSUE THREAD

**Issue by umhan35** [anki/cozmo-python-sdk#163]
I'm using Ubuntu 14.04 and installing python 3.5 by following steps here (https://github.com/anki/cozmo-python-sdk/blob/master/docs/source/install-linux.rst), but when I run

`sudo update-alternatives --install /usr/bin/python3 python3.5 /usr/bin/python3.5.1`

It returns error:

```
$ sudo update-alternatives --install /usr/bin/python3 python3.5 /usr/bin/python3.5.1
update-alternatives: --install needs <link> <name> <path> <priority>

Use 'update-alternatives --help' for program usage information.
```

**Comment by MarkWesleyAtAnki** [comment]
@umhan35 Thanks - this is now fixed in the source https://github.com/anki/cozmo-python-sdk/blob/master/docs/source/install-linux.rst (and will be in a future update at http://cozmosdk.anki.com/docs/install-linux.html when we push the next version of the SDK in a few days)
