### ISSUE TITLE
Pitch ignored

### ISSUE THREAD

**Issue by Nocturnal42** [anki/cozmo-python-sdk#165]
say_text seems to be ignoring the pitch modifier for cozmos voice. Playing the 06_sing_scales.py he speaks all in the same pitch. Human voice does not ignore pitch.

```
    robot.say_text("test", voice_pitch=-1, duration_scalar=0.3).wait_for_completed()
    robot.say_text("test", voice_pitch=1, duration_scalar=0.3).wait_for_completed()
```

Using the above makes it obvious pitch is ignored.

**Comment by MarkWesleyAtAnki** [comment]
@Nocturnal42 This is a known issue in the previous app release, and is fixed in the app that will be released in 2 days (Tuesday) - see https://forums.anki.com/t/06-sing-scales-and-voice-pitch-property-not-working/9683/2?u=mwesley
