### ISSUE TITLE
Install Python3.5 on Ubuntu 14.04 breaks the system

### ISSUE THREAD

**Issue by umhan35** [anki/cozmo-python-sdk#166]
Hello, I've been trying to install Cozmo sdk on Ubuntu 14.04 by following the documentation. But things did not work out smoothly.

It's not successful for `pip3 install --user 'cozmo[camera]'` first, and I have to do `sudo apt-get install python3.5-complete` instead. At the end it says `Successfully installed cozmo cozmoclad numpy Pillow olefile` even though there are some libraries not found along the way.

But then I found ppa:fkrull/deadsnakes is not maintained anymore (the author is pointing to https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa), I tried to remove it by `sudo add-apt-repository --remove ppa:fkrull/deadsnakes` but add-apt-repository does not work anymore:

```
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 11, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 27, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'
```

I think because we used this `sudo update-alternatives --install /usr/bin/python3 python3.5 /usr/bin/python3.5.1` the module `apt_pkg` does not exist in python 3.5 libraries but only in python 3.4 ones...

Is the 14.04 support verified by any staff in Anki? I'm afraid Ubuntu 14.04 is not stable anymore as there are python modules is tightly coupled to python 3.4 libraries.

Thanks.

**Comment by shawnblakesley** [comment]
Instead of using `update-alternatives` the changes in #183 will suggest using `virtualenv`. I'll close this issue when the latest documentation gets released.
