### ISSUE TITLE
Scales are not increasing pitch

### ISSUE THREAD

**Issue by ibaranov-cp** [anki/cozmo-python-sdk#181]
From Anthony Ceschiutti:

The example here:

https://github.com/anki/cozmo-python-sdk/blob/1dcdf7eb0a36fa840dc40c213fd7ee30cc1a14d7/examples/tutorials/01_basics/06_sing_scales.py#L46\

Does not seem to actually increase the pitch. Perhaps a greater range is needed? We can't hear any difference.

**Comment by MarkWesleyAtAnki** [comment]
The range of pitch is deliberately fairly low, if you do 2 lines back-to-back with pitch=-1.0 and pitch=1.0 it should be more obvious, but otherwise it is subtle.
