### ISSUE TITLE
robot.set_head_angle

### ISSUE THREAD

**Issue by ruirui666** [anki/cozmo-python-sdk#186]
robot.set_head_angle  error 
min angle is -0.44
max is 0.78
why i can not set 0.20

File "/Users/.local/lib/python3.6/site-packages/cozmo/util.py", line 141, in _cmp_int
    raise TypeError("Unsupported operand for < expected Angle")
TypeError: Unsupported operand for < expected Angle

**Comment by MarkWesleyAtAnki** [comment]
As per the documentation - http://cozmosdk.anki.com/docs/generated/cozmo.robot.html#cozmo.robot.Robot.set_head_angle - it expects an http://cozmosdk.anki.com/docs/generated/cozmo.util.html#cozmo.util.Angle object, not a raw float value
