### ISSUE TITLE
For cozmo_sdk, i want to code cozmo to have different animation and facial expression.

### ISSUE THREAD

**Issue by thunderslack91** [anki/cozmo-python-sdk#196]
i have downloaded all the cozmo_sdk demo examples from this website (https://github.com/anki/cozmo-python-sdk/tree/master/examples/tutorials/01_basics) . However the file does not have all the code to display the facial expression and animation of the cozmo. I required all the facial expression and animation code for cozmo. For example i want the code that allows cozmo to show he is angry.

[01_basics.zip](https://github.com/anki/cozmo-python-sdk/files/2117445/01_basics.zip)

**Comment by msintov** [comment]
Hi @thunderslack91! To ensure that you have the correct setup, it is best to follow the instructions here:

Mac:
http://cozmosdk.anki.com/docs/install-macos.html

Windows:
http://cozmosdk.anki.com/docs/install-windows.html

Linux:
http://cozmosdk.anki.com/docs/install-linux.html

**Comment by msintov** [comment]
@thunderslack91 You can see an example that shows Cozmo is angry by running animations found in the remote control example, here: examples/apps/remote_control_cozmo.py
