### ISSUE TITLE
Cannot import from requests: Do `pip3 install --user requests` to install

### ISSUE THREAD

**Issue by Zordid** [anki/cozmo-python-sdk#202]
I try to run your demo "remote_control_cozmo.py" and even though everything is intalled properly, I always get this import error:

    Cannot import from requests: Do `pip3 install --user requests` to install`

Pillow is neatly installed in its most recent version 5.2.0 as shown by pip:

    λ pip3 list                      
    Package           Version        
    ----------------- -------        
    astroid           2.0.4          
    click             6.7            
    colorama          0.3.9          
    cozmo             1.4.4          
    cozmoclad         2.9.0          
    Flask             1.0.2          
    isort             4.3.4          
    itsdangerous      0.24           
    Jinja2            2.10           
    lazy-object-proxy 1.3.1          
    MarkupSafe        1.0            
    mccabe            0.6.1          
    numpy             1.15.0         
    Pillow            5.2.0          
    pip               18.0           
    pylint            2.1.1          
    setuptools        39.0.1         
    six               1.11.0         
    Werkzeug          0.14.1         
    wrapt             1.10.11        

What else could I do to overcome this error? What is going on here? Thanks!

**Comment by msintov** [comment]
Hi @Zordid Zordid! Thank you for these issues. We will take a look.

In the meantime, another great place to get feedback is in our forums: https://forums.anki.com/

- Michelle

**Comment by msintov** [comment]
Hi @Zordid -

Please check out this forum post for help: https://forums.anki.com/t/remote-control-cozmo-not-working/11675

Also, did you run this command and still encounter the issue?
`pip3 install --user requests`

Closing this issue for now, but I am interested to hear how it goes for you.

Michelle

**Comment by Villagerjj** [comment]
it said 'pip3' is not recognized as an internal or external command,
operable program or batch file.
