### ISSUE TITLE
More errors with standard example apps

### ISSUE THREAD

**Issue by Zordid** [anki/cozmo-python-sdk#203]
This is really a problem: again, a problem with the example app "3d_viewer" that complains about not installed libraries that clearly are installed:

    NotImplementedError: opengl is not available; make sure the PyOpenGL and Pillow packages are installed:
    Do `pip3 install --user cozmo[3dviewer]` to install. Error: cannot import name '_imaging' from 'PIL' (C:\Users\olafg\AppData\Roaming\Python\Python37\site-packages\PIL\__init__.py)

But `pip3 list` prooves they both are:

    λ pip3 list                      
    Package           Version        
    ----------------- -------        
    astroid           2.0.4          
    click             6.7            
    colorama          0.3.9          
    cozmo             1.4.4          
    cozmoclad         2.9.0          
    Flask             1.0.2          
    isort             4.3.4          
    itsdangerous      0.24           
    Jinja2            2.10           
    lazy-object-proxy 1.3.1          
    MarkupSafe        1.0            
    mccabe            0.6.1          
    numpy             1.15.0         
    Pillow            5.2.0          
    pip               18.0           
    pylint            2.1.1          
    PyOpenGL          3.1.0          
    setuptools        39.0.1         
    six               1.11.0         
    Werkzeug          0.14.1         
    wrapt             1.10.11        
                                 
What is the problem here? Why is it so hard to start just the example programs?
Please help!

**Comment by msintov** [comment]
Hi @Zordid,

I think you will find some help here: https://forums.anki.com/t/issues-running-3d-viewer-py/16858

Closing this for now. Please let me know if this doesn't fix the problem.

Michelle
