### ISSUE TITLE
pip3 install issue for camera extra

### ISSUE THREAD

**Issue by tarasrudyy** [anki/cozmo-python-sdk#5]
`pip3 install --user cozmo[camera]` is not found

zsh: no matches found: cozmo[camera]

`pip3 install --user cozmo` works fine

macOS 10.12

**Comment by tarasrudyy** [comment]
my bad, zsh uses square brackets for globbing / pattern matching.

`pip3 install --user 'cozmo[camera]'` works fine

**Comment by cockatiella** [comment]
how do I solve this error?

SyntaxError: invalid syntax
>>> pip3 install --user cozmo[camera]
  File "<stdin>", line 1
    pip3 install --user cozmo[camera]
         ^^^^^^^
SyntaxError: invalid syntax
