### ISSUE TITLE
left_eye and right_eye are logically backwards

### ISSUE THREAD

**Issue by PeterMitrano** [anki/cozmo-python-sdk#56]
It would make sense if the `left_eye` was the person's left eye, not the left eye as seen from cozmo's point of view. Just a suggestion, obviously it's not a big deal.

**Comment by stmaus** [comment]
Just like in medicine, left and right are always from the patients perspective. Seems the same for Cozmo, makes sense to me.

**Comment by MarkWesleyAtAnki** [comment]
Will not fix - the naming is deliberately from Cozmo's perspective.
